language: objective-c
xcode_project: SpatialConnect.xcodeproj
xcode_scheme: SpaconAppTest

osx_image: xcode8
notifications:
  email:
    - spatialconnect@boundlessgeo.com

before_script:
  - carthage bootstrap

script:
  - xcodebuild clean build -project SpatialConnect.xcodeproj -scheme SpatialConnect -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -quiet
  - xcodebuild test -project SpatialConnect.xcodeproj -scheme SpatialConnect -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
