language: objective-c
xcode_project: SpatialConnect.xcodeproj
xcode_scheme: SpaconAppTest

osx_image: xcode8
notifications:
  email:
    - spatialconnect@boundlessgeo.com

before_script:
  - carthage bootstrap

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

script:
  - xcodebuild -project SpatialConnect.xcodeproj -scheme SpaconAppTest test -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' -quiet
